# -*- coding: utf-8 -*-
"""AB_Testing_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jf8xtz0oifwLz-2qGJCX2QYK7fpd3d-8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv("ab_data.csv")
df.head()

df.info()



df.shape

df.columns

df.isnull().sum()

df.columns

df.columns = df.columns.str.strip().str.lower()
df.columns

df['variant'].value_counts()

control =df[df['variant'] == 'control']
treatment = df[df['variant'] == 'treatment']

control = df[df['variant'] == 'A']
treatment = df[df['variant'] == 'B']

print("Control size:",len(control))
print("Treatment size:",len(treatment))

control_rate = control['converted'].mean()
treatment_rate = treatment['converted'].mean()

print("Control Conversion Rate:",control_rate)
print("Treatment Conversion Rate:",treatment_rate)

lift = treatment_rate - control_rate
print("Conversion Lift:", lift)

rates = [control_rate,treatment_rate]
labels = ['Control','Treatment']

import matplotlib.pyplot as plt

plt.bar(labels,rates)
plt.ylabel("Conversion Rate")
plt.title("A/B Testing Conversion Comparison")
plt.show()

from scipy import stats

stat, p_value = stats.ttest_ind(
    treatment['converted'],
    control['converted']
)

print("T-statistics:",stat)
print("P-value:",p_value)

if p_value < 0.05:
  print("result is statistically significant ")
else:
  print("result is NOT statistically significant")

alpha = 0.05

if p_value < alpha:
  print("Result is statistically significant ")
  print("Reject Null Hypothesis")
  print("There is a difference in conversion rates")
else:
  print("result is NOT sttaistically significant")
  print("Fails to Reject Null Hypothesis")
  print("No strong difference in conversion rates")

conversion_rates = df.groupby('variant')['converted'].mean()

print(conversion_rates)

import matplotlib.pyplot as plt

conversion_rates.plot(kind='bar')

plt.title("Conversion Rate by variant")
plt.xlabel("Variant")
plt.ylabel("Conversion Rate")
plt.show()

control_rate = conversion_rates['A']
experiment_rate = conversion_rates['B']

print("Control Conversion Rates:",control_rate)
print("Experiment Conversion Rate :",experiment_rate)

if experiment_rate > control_rate:
  print("variant B performed better ")
else:
  print("variant A performed better")

lift = (experiment_rate - control_rate) / control_rate * 100

print("Conversion Lift %:",lift)

import os
os.listdir()

import os
os.listdir()

import pandas as pd

df = pd.read_csv("sample_ab_test.csv")
df.head()

df.columns = df.columns.str.strip().str.lower()

conversion_rates = df.groupby('variant')['converted'].mean()
print(conversion_rates)

import matplotlib.pyplot as plt

conversion_rates.plot(kind='bar')

plt.title("Conversion Rate by variant")
plt.xlabel("Variant")
plt.ylabel("Converion Rate")

plt.savefig("conversion_chart.png")

plt.show()

import os
os.listdir()

plt.savefig("/content/conversion_chart.png")

os.listdir("/content")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.stats.proportion import proportions_ztest

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("sample_ab_test.csv")
df.head()

df.columns

df.info()
df.isnull().sum()

conversion_rates = df.groupby('variant')['converted'].mean()

print("Conversion Rates:")
print(conversion_rates)

conversions = df.groupby('variant')['converted'].sum()

users = df.groupby('variant')['converted'].count()

z_stat, p_value = proportions_ztest(conversions, users)

print("Z-Statistic:",z_stat)
print("P-Value:",p_value)

alpha = 0.05

if p_value < alpha:
  print("result: Significant differemce - New variant performs better")
else:
  print("Result: No significant difference - Keep original variant")

